version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - '1935:1935' # RTMP
      - '8080:8080' # HLS / HTTP
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - hls_data:/mnt/hls
    restart: always

  nest:
    build: ./nest
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/live_db
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: live_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
  hls_data:
